// @ts-nocheck
export const propertyTypes = [
  {
    'id': 'small-lot-apartments-01',
    'name': 'Small Lot Apartments 01',
    'description': 'Small Lot Apartments 01 by Collins and Turner',
    'icon': '🏙️',
    'floors': 1,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Small Lot Apartments 01',
    'architect': 'Collins and Turner',
    'category': 'mid-rise',
    'housingType': 'small',
    'fsr': 2,
    'minLotWidth': 13,
    'minLotArea': 520,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-11/small-lot-apartments-01-collins-and-turner-2200x900.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/modern_house_01-v4.glb',
    'frontOffset': 0,
    'houses': '7-13',
    'beds': '4-8',
    'size': '520-904 m2'
  },
  {
    'id': 'small-lot-apartments-02',
    'name': 'Small Lot Apartments 02',
    'description': 'Small Lot Apartments 02 by Nguluway DesignInc',
    'icon': '🏙️',
    'floors': 3,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Small Lot Apartments 02',
    'architect': 'Nguluway DesignInc',
    'category': 'mid-rise',
    'housingType': 'small',
    'fsr': 2,
    'minLotWidth': 13.6,
    'minLotArea': 571,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-11/small-lot-apartments-02-nguluway-designinc-2200x900.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/modern_house_01-v4.glb',
    'frontOffset': 0,
    'houses': '6-14',
    'beds': '5',
    'size': '571-863 m2'
  },
  {
    'id': 'small-lot-apartments-03',
    'name': 'Small Lot Apartments 03',
    'description': 'Small Lot Apartments 03 by MHN Design Union',
    'icon': '🏙️',
    'floors': 4,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Small Lot Apartments 03',
    'architect': 'MHN Design Union',
    'category': 'mid-rise',
    'housingType': 'small',
    'fsr': 2,
    'minLotWidth': 16,
    'minLotArea': 640,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-11/small-lot-apartments-03-mhn-design-union-2200x900.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/SLA03.glb',
    // Taller than it is wide (21.7m high on a 14.5m frontage), so the
    // "height = smallest dimension" guess in measureAndFit() would lay it on its
    // side. The GLB is Y-up, per the glTF standard.
    'heightAxis': 'y',
    'frontOffset': 0,
    'houses': '9-24',
    'beds': '4-10',
    'size': '640-1287 m2'
  },
  {
    'id': 'small-lot-apartments-04',
    'name': 'Small Lot Apartments 04',
    'description': 'Small Lot Apartments 04 by Neeson Murcutt Neille',
    'icon': '🏙️',
    'floors': 4,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Small Lot Apartments 04',
    'architect': 'Neeson Murcutt Neille',
    'category': 'mid-rise',
    'housingType': 'small',
    'fsr': 2,
    'minLotWidth': 16.5,
    'minLotArea': 600,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-11/small-lot-apartments-04-neeson-murcutt-neille-2200x900.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/modern_house_01-v4.glb',
    'frontOffset': 0,
    'houses': '6-21',
    'beds': '1-7',
    'size': '600-1028 m2'
  },
  {
    'id': 'corner-lot-apartments-01',
    'name': 'Corner Lot Apartments 01',
    'description': 'Corner Lot Apartments 01 by Tonkin Zulaikha Greer',
    'icon': '🏙️',
    'floors': 4,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Corner Lot Apartments 01',
    'architect': 'Tonkin Zulaikha Greer',
    'category': 'mid-rise',
    'housingType': 'corner',
    'fsr': 2,
    'minLotWidth': 15,
    'minLotArea': 525,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-11/corner-lot-apartments-01-tonkin-zulaikha-greer-2200x900.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/modern_house_01-v4.glb',
    'frontOffset': 0,
    'houses': '9-21',
    'beds': '4-18',
    'size': '525-1050 m2'
  },
  {
    'id': 'corner-lot-apartments-02',
    'name': 'Corner Lot Apartments 02',
    'description': 'Corner Lot Apartments 02 by Spacecraft Architects',
    'icon': '🏙️',
    'floors': 4,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Corner Lot Apartments 02',
    'architect': 'Spacecraft Architects',
    'category': 'mid-rise',
    'housingType': 'corner',
    'fsr': 2,
    'minLotWidth': 17.9,
    'minLotArea': 614,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-11/corner-lot-apartments-02-spacecraft-architects-2200x900.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/modern_house_01-v4.glb',
    'frontOffset': 0,
    'houses': '10-24',
    'beds': '6-11',
    'size': '614-1287 m2'
  },
  {
    'id': 'large-lot-apartments-01',
    'name': 'Large Lot Apartments 01',
    'description': 'Large Lot Apartments 01 by Silvester Fuller',
    'icon': '🏙️',
    'floors': 4,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Large Lot Apartments 01',
    'architect': 'Silvester Fuller',
    'category': 'mid-rise',
    'housingType': 'large',
    'fsr': 2,
    'minLotWidth': 49.1,
    'minLotArea': 1610,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-11/large-lot-apartments-01-silvester-fuller-2200x900.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/modern_house_01-v4.glb',
    'frontOffset': 0,
    'houses': '20-40',
    'beds': '13-53',
    'size': '1610-2338 m2'
  },
  {
    'id': 'large-lot-apartments-02',
    'name': 'Large Lot Apartments 02',
    'description': 'Large Lot Apartments 02 by Bennett and Trimble',
    'icon': '🏙️',
    'floors': 3,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Large Lot Apartments 02',
    'architect': 'Bennett and Trimble',
    'category': 'mid-rise',
    'housingType': 'large',
    'fsr': 2,
    'minLotWidth': 36,
    'minLotArea': 2052,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-11/large-lot-apartments-02-bennett-and-trimble-2200x900_0.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/modern_house_01-v4.glb',
    'frontOffset': 0,
    'houses': '24-216',
    'beds': '15-100',
    'size': '2052-12040 m2'
  },
  {
    'id': 'large-lot-apartments-03',
    'name': 'Large Lot Apartments 03',
    'description': 'Large Lot Apartments 03 by Andrew Burges Architects',
    'icon': '🏙️',
    'floors': 4,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Large Lot Apartments 03',
    'architect': 'Andrew Burges Architects',
    'category': 'mid-rise',
    'housingType': 'large',
    'fsr': 2,
    'minLotWidth': 67,
    'minLotArea': 3551,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-11/large-lot-apartments-03-andrew-burges-architects-2200x900.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/modern_house_01-v4.glb',
    'frontOffset': 0,
    'houses': '58-140',
    'beds': '30-120',
    'size': '3551-6566 m2'
  },
  {
    'id': 'semis-01',
    'name': 'Semis 01',
    'description': 'Semis 01 by Anthony Gill Architects',
    'icon': '🏙️',
    'floors': 2,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Semis 01',
    'architect': 'Anthony Gill Architects',
    'category': 'mid-rise',
    'housingType': 'semis',
    'fsr': 2,
    'minLotWidth': 12,
    'minLotArea': 450,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-07/semis-01-anthony-gill-architects-2200x900.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/SD01.glb',
    'frontOffset': 0,
    'houses': '2',
    'beds': '3-4',
    'size': '400 m2'
  },
  {
    'id': 'semis-02',
    'name': 'Semis 02',
    'description': 'Semis 02 by Sibling Architecture',
    'icon': '🏙️',
    'floors': 2,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Semis 02',
    'architect': 'Sibling Architecture',
    'category': 'mid-rise',
    'housingType': 'semis',
    'fsr': 2,
    'minLotWidth': 12,
    'minLotArea': 450,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-07/semis-02-sibling-architecture-2200x900.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/modern_house_01-v4.glb',
    'frontOffset': 0,
    'houses': '2',
    'beds': '2-4',
    'size': '400 m2'
  },
  {
    'id': 'terraces-01',
    'name': 'Terraces 01',
    'description': 'Terraces 01 by Carter Williamson',
    'icon': '🏙️',
    'floors': 2,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Terraces 01',
    'architect': 'Carter Williamson',
    'category': 'mid-rise',
    'housingType': 'terraces',
    'fsr': 2,
    'minLotWidth': 15,
    'minLotArea': 500,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-07/terraces-01-carter-williamson-2200x900.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/TH01.glb',
    'frontOffset': 0,
    'houses': '3',
    'beds': '3-4',
    'size': '150 m2'
  },
  {
    'id': 'terraces-02',
    'name': 'Terraces 02',
    'description': 'Terraces 02 by Sam Crawford Architects',
    'icon': '🏙️',
    'floors': 2,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Terraces 02',
    'architect': 'Sam Crawford Architects',
    'category': 'mid-rise',
    'housingType': 'terraces',
    'fsr': 2,
    'minLotWidth': 18.5,
    'minLotArea': 515,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-07/terraces-02-sam-crawford-architects-2200x900.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/TH02.glb',
    'frontOffset': 0,
    'houses': '3',
    'beds': '2-4',
    'size': '150 m2'
  },
  {
    'id': 'terraces-03',
    'name': 'Terraces 03',
    'description': 'Terraces 03 by Officer Woods Architects',
    'icon': '🏙️',
    'floors': 2,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Terraces 03',
    'architect': 'Officer Woods Architects',
    'category': 'mid-rise',
    'housingType': 'terraces',
    'fsr': 2,
    'minLotWidth': 18,
    'minLotArea': 500,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-07/terraces-03-officer-woods-architects-2200x900.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/modern_house_01-v4.glb',
    'frontOffset': 0,
    'houses': '3',
    'beds': '2-5',
    'size': '150 m2'
  },
  {
    'id': 'terraces-04',
    'name': 'Terraces 04',
    'description': 'Terraces 04 by Other Architects x NMBW',
    'icon': '🏙️',
    'floors': 2,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Terraces 04',
    'architect': 'Other Architects x NMBW',
    'category': 'mid-rise',
    'housingType': 'terraces',
    'fsr': 2,
    'minLotWidth': 18,
    'minLotArea': 595,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-08/terraces-04-other-architects-x-nmbw-2200x900_0.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/modern_house_01-v4.glb',
    'frontOffset': 0,
    'houses': '3',
    'beds': '2-5',
    'size': '150 m2'
  },
  {
    'id': 'row-homes-01',
    'name': 'Row Homes 01',
    'description': 'Row Homes 01 by SAHA',
    'icon': '🏙️',
    'floors': 2,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Row Homes 01',
    'architect': 'SAHA',
    'category': 'mid-rise',
    'housingType': 'row-homes',
    'fsr': 2,
    'minLotWidth': 13,
    'minLotArea': 500,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-07/row-homes-01-saha-2200x900.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/RH01.glb',
    'frontOffset': 0,
    'houses': '4',
    'beds': '2-3',
    'size': '200 m2'
  },
  {
    'id': 'manor-homes-01',
    'name': 'Manor Homes 01',
    'description': 'Manor Homes 01 by Studio Johnston',
    'icon': '🏙️',
    'floors': 2,
    'defaultWidth': 20,
    'defaultDepth': 20,
    'patternBook': 'Manor Homes 01',
    'architect': 'Studio Johnston',
    'category': 'mid-rise',
    'housingType': 'manor-homes',
    'fsr': 2,
    'minLotWidth': 15,
    'minLotArea': 625,
    'color': '#E8E0D5',
    'accentColor': '#5D4037',
    'windowColor': '#4A6B8A',
    'hasPitchedRoof': false,
    'hasSetback': true,
    'hasBalconies': true,
    'materials': 'Brick, render',
    'image': 'https://www.planning.nsw.gov.au/sites/default/files/2025-07/manor-homes-01-studio-johnston-2200x900.jpg',
    'model': 'https://io.imsstratus.com.au/upapp/app/js/models/modern_house_01-v4.glb',
    'frontOffset': 0,
    'houses': '4',
    'beds': '1-3',
    'size': '600 m2'
  }
];
// Which up_property_d_3 `*_eligible` columns make each pattern book available for
// a property. A design is eligible when ANY of its columns is true (several books
// have separate storey variants). Mirrors `pattern_book_options` in Property.svelte.
export const patternBookEligibilityColumns = {
  'small-lot-apartments-01': [
    'small_lot_apt_01_3storeys_eligible',
    'small_lot_apt_01_3storeys_min_eligible',
    'small_lot_apt_01_4storeys_eligible'
  ],
  'small-lot-apartments-02': [
    'small_lot_apt_02_3storeys_eligible',
    'small_lot_apt_02_4storeys_eligible'
  ],
  'small-lot-apartments-03': ['small_lot_apt_03_4_6storeys_eligible'],
  'small-lot-apartments-04': ['small_lot_apt_04_4_5storeys_eligible'],
  'corner-lot-apartments-01': ['corner_lot_apt_01_4_6storeys_eligible'],
  'corner-lot-apartments-02': ['corner_lot_apt_02_4_6storeys_eligible'],
  'large-lot-apartments-01': [
    'large_lot_apt_01_4storeys_eligible',
    'large_lot_apt_01_6storeys_eligible'
  ],
  'large-lot-apartments-02': [
    'large_lot_apt_02_3_4storeys_eligible',
    'large_lot_apt_02_5_6storeys_eligible'
  ],
  'large-lot-apartments-03': ['large_lot_apt_03_4_6storeys_eligible'],
  'semis-01': ['semis_01_anthony_gill_eligible'],
  'semis-02': ['semis_02_sibling_eligible'],
  'terraces-01': ['terraces_01_carter_eligible'],
  'terraces-02': ['terraces_02_sam_crawford_eligible'],
  'terraces-03': ['terraces_03_officer_woods_eligible'],
  'terraces-04': ['terraces_04_other_eligible'],
  'row-homes-01': ['row_homes_01_saha_eligible'],
  'manor-homes-01': ['manor_homes_01_studio_eligible']
};

// True when the property may use this pattern book. Falls back to the lot-area
// minimum when the property has no eligibility columns at all (older payloads).
export function isDesignEligible(property, design) {
  if (!property) return true;
  const columns = patternBookEligibilityColumns[design.id];
  if (columns && columns.some(c => c in property)) {
    return columns.some(c => Boolean(property[c]));
  }
  if (property.area && design.minLotArea) return property.area >= design.minLotArea;
  return true;
}
