<script lang="ts">
  // @ts-nocheck
	// Shell for the merged property app: its own global stylesheet (minireset,
	// incremental, style, balloon), Typekit and Lucide icon font — exactly what
	// upapp's app.html loaded — and none of the marketing site's chrome.
	// The app's stylesheets are imported here (not <link>ed from static/) so Vite
	// bundles them in this order and hot-reloads edits without a hard refresh.
	// global.css pulls in minireset, incremental, style and balloon; theme.css is
	// generated by scripts/app-theme.py; skin.css restyles the app to the site.
	// Each file is imported directly (not via global.css's @imports) so every one
	// passes through vite.config.ts's scope-app-css transform. Same order as before.
	import '$lib/app/css/minireset.min.css';
	import '$lib/app/css/incremental.css';
	import '$lib/app/css/style.css';
	import '$lib/app/css/balloon.min.css';
	import '$lib/app/css/theme.css';
	import '$lib/app/css/skin.css';
	let { children } = $props();
</script>

<svelte:head>
	<link rel="stylesheet" href="/app/css/lucide/lucide.css" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, viewport-fit=cover" />
	<meta name="robots" content="noindex" />
</svelte:head>

<div class="up-app">
	{@render children()}
</div>

<style>
	/* The site's Tailwind preflight and tokens are global. Colours come from
	   /app/css/theme.css (generated by scripts/app-theme.py): light = the app's
	   original palette, dark = derived; the site's data-theme / system preference
	   selects. Typography is Geist, matching the marketing site. */
	/* Page ground follows the site's own theme tokens (--bg/--fg swap with data-theme). */
	:global(html:has(.up-app)), :global(html:has(.up-app) body) { background: var(--bg); color: var(--fg); }
	:global(html:has(.up-app) .grain) { display: none; }
	:global(.up-app) { --up-bg: var(--bg); --up-fg: var(--fg); background: var(--bg); color: var(--fg); min-height: 100dvh; }
	:global(.up-app), :global(html:has(.up-app) body) { --font-family: var(--font-sans); font-family: var(--font-sans); font-weight: 400; font-size: 16px; -webkit-font-smoothing: antialiased; }
	:global(.up-app input), :global(.up-app select), :global(.up-app textarea), :global(.up-app button) { font-family: inherit; }
	:global(.up-app h1), :global(.up-app h2), :global(.up-app h3) { font-weight: 600; letter-spacing: -0.01em; }
	:global(.up-app i[class^='icon-']), :global(.up-app i[class*=' icon-']) { font-family: 'lucide' !important; }
</style>
